#Gives permission to install Salesforce CLI
sudo: true

before_install:

#Install Salesforce CLI
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- mkdir sfdx
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH

script:
#Install sfdx-git-delta
- npm install sfdx-git-delta@latest --global

#Generate diff
- mkdir changed-sources
- sgd --to HEAD --from HEAD^ --repo . --output changed-sources/ --generate-delta
- cat changed-sources/package/package.xml
- cat changed-sources/destructiveChanges/destructiveChanges.xml

#Push changed-sources
- echo "machine github.com login $REPO_LOGIN password $REPO_PASSWORD" > $HOME/.netrc
- git add changed-sources/*
- git commit -m 'Changed sources'
- git push origin master