#Gives permission to install Salesforce CLI
sudo: true

before_install:

#Install Salesforce CLI
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- mkdir sfdx
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH

before_script:

#Authorize target deployment org
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername --setalias CI

script:

#Deploy files
- sfdx force:source:convert --rootdir ci --outputdir src
- sfdx force:mdapi:deploy --deploydir src --targetusername CI --wait 10 --singlepackage
- sfdx force:mdapi:deploy --deploydir destructiveChanges --targetusername CI --wait 10 --singlepackage