#Gives permission to install Salesforce CLI
sudo: true

before_install:

#Install Salesforce CLI
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- mkdir sfdx
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH

before_script:

#Install sfdx-git-delta
- npm install sfdx-git-delta@latest --global

#Authorize target deployment org
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername --setalias CI

script:

#Generate diffs
- mkdir changed-sources
- sgd --to HEAD --from HEAD^ --repo . --output changed-sources/ --generate-delta
- cat changed-sources/ci/main/default/objects/Account/fields/Test__c.field-meta.xml
- cat changed-sources/package/package.xml
- cat changed-sources/destructiveChanges/destructiveChanges.xml

#Deploy files
- sfdx force:source:deploy --sourcepath changed-sources/ci --targetusername CI --wait 10
- sfdx force:mdapi:deploy --deploydir changed-sources/destructiveChanges --targetusername CI --wait 10